server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8 # í•œê¸€ ì¸ì½”ë”©
      enabled: true # ì¸ì½”ë”© í™œì„±í™”
      force: true  # ìš”ì²­/ì‘ë‹µ ëª¨ë‘ UTF-8 ê°•ì œ ì ìš© (í•œê¸€ ê¹¨ì§ ë°©ì§€)

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shoppingmall_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: dev
    password: dev1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true  # âœ… Hibernateê°€ í…Œì´ë¸” ë§Œë“  í›„ data.sql ì‹¤í–‰
    hibernate:
      ddl-auto: create
      #ddl-auto: update # í…Œì´ë¸” ì—†ìœ¼ë©´ ìƒì„±, ìˆìœ¼ë©´ ìˆ˜ì •
      #ddl-auto: validate # ì—”í‹°í‹°ì™€ DBìŠ¤í‚¤ë§ˆì˜ ì¼ì¹˜ ì—¬ë¶€ë§Œ ê²€ì¦
    show-sql: true
    properties:
      hibernate.format_sql: true
      use_sql_comments: true
      dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always        # ğŸš€ data.sql ì‹¤í–‰ í™œì„±í™”
      encoding: UTF-8
      continue-on-error: false  # âœ… ì—ëŸ¬ ë°œìƒ ì‹œ ì¦‰ì‹œ ì¤‘ë‹¨ (ë””ë²„ê¹…ìš©)

logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG  # ğŸ” data.sql ì‹¤í–‰ ë¡œê·¸
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

token:
  secret:
    key: SpringSecurityKey_P_ssword_http__Spring_io
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12