server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8 # 한글 인코딩
      enabled: true # 인코딩 활성화
      force: true  # 요청/응답 모두 UTF-8 강제 적용 (한글 깨짐 방지)

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true  # Hibernate가 테이블 만든 후 data.sql 실행
    hibernate:
      ddl-auto: create
      #ddl-auto: update # 테이블 없으면 생성, 있으면 수정
      #ddl-auto: validate # 엔티티와 DB스키마의 일치 여부만 검증
    show-sql: true
    properties:
      hibernate.format_sql: true
      use_sql_comments: true
      dialect: org.hibernate.dialect.MySQL8Dialect
  # Redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  sql:
    init:
      mode: always        # data.sql 실행 활성화
      encoding: UTF-8
      continue-on-error: false  # 에러 발생 시 즉시 중단 (디버깅용)


  # OAuth2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            user-name-attribute: sub


logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG  # data.sql 실행 로그
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.amazonaws: DEBUG
    com.shoppingmall.ecommerceapi.common.infra: DEBUG

token:
  secret:
    key: ${TOKEN_SECRET_KEY}
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12

oauth2:
  redirect-url: ${OAUTH2_REDIRECT_URL:http://localhost:8080/swagger-ui/index.html}
  failure-redirect-url: ${OAUTH2_FAILURE_REDIRECT_URL:http://localhost:8080/swagger-ui/index.html?error=true}

cloud:
  aws:
    credentials:
      access-key: ${CLOUD_AWS_ACCESS_KEY}
      secret-key: ${CLOUD_AWS_SECRET_KEY}
    s3:
      bucket: ${S3_IMAGE_BUCKET}
      endpoint: https://s3.ap-northeast-2.amazonaws.com # 추가: 리전 엔드포인트 명시
    region:
      static: ap-northeast-2
    stack:
      auto: false