name: Shopping Mall CI/CD

on:
  push:
    branches: [ "main" ] # main 브랜치에 push될 때 작동

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1. 도커 이미지 빌드 및 푸시
      - name: Build and Push Docker Image
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-app .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-app

      # 2. EC2에 접속해서 새 이미지로 교체 및 환경 변수 주입
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          # GitHub Secrets에 저장된 변수들을 SSH 세션으로 가져옵니다.
          envs:
            envs: CLOUD_AWS_ACCESS_KEY,CLOUD_AWS_SECRET_KEY,DB_URL,DB_USERNAME,DB_PASSWORD,TOKEN_SECRET_KEY,GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET
          script: |
            # 1. 기존 컨테이너 중지
            sudo docker-compose down
            
            # 2. 최신 이미지 받아오기
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-app
            
            # 3. .env 파일 생성 (도커 컴포즈가 이 파일을 읽어서 앱에 전달합니다)
            echo "CLOUD_AWS_ACCESS_KEY=$CLOUD_AWS_ACCESS_KEY" > .env
            echo "CLOUD_AWS_SECRET_KEY=$CLOUD_AWS_SECRET_KEY" >> .env
            echo "DB_URL=$DB_URL" >> .env
            echo "DB_USERNAME=$DB_USERNAME" >> .env
            echo "DB_PASSWORD=$DB_PASSWORD" >> .env
            echo "TOKEN_SECRET_KEY=$TOKEN_SECRET_KEY" >> .env
            echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" >> .env
            echo "GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET" >> .env
            echo "REDIS_HOST=redis" >> .env
            echo "REDIS_PORT=6379" >> .env
            
            # 4. 컨테이너 실행
            sudo docker-compose up -d